version: '3.8'

services:

  mauticdb:
    image: percona/percona-server:5.7
    container_name: mauticdb
    volumes:
      - mautic/mysql_data:/var/lib/mysql
    deploy:
      update_config:
        #Inicia o container e depois deleta o antigo
        order: start-first
        #Em falha, volta para o último estado funcional
        failure_action: rollback
    environment:
      - MYSQL_ROOT_PASSWORD=mysecret
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - mautic-net

  mautic:
    image: mautic/mautic:latest
    container_name: mautic
    depends_on:
      - mauticdb
    ports:
      - 8081:80
    volumes:
      - mautic2/mautic_data:/var/www/html
    deploy:
      update_config:
        #Inicia o container e depois deleta o antigo
        order: start-first
        #Em falha, volta para o último estado funcional
        failure_action: rollback

    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mysecret
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
    networks:
      - mautic-net

networks:
  mautic-net:
    driver: bridge

deploy: